In [3]:
import numpy as np
def gaussian_fourier_tranform(w: np.array)-> float:
    '''
    W array 
    ''' 
    D = len(w)
    norm = w.dot(w)
    return (2*np.pi)**(-D/2)* np.exp(-norm/2)

# debería de ser menor que 0 0 igua

In [4]:
w = np.array([1,0])

gaussian_fourier_tranform(w)



0.09653235263005391

In [5]:
size, dimension = 5, 10


def generate_random(p, dimension, k = 2): 
    '''
    '''
    while True: # 
        w = np.random.uniform(-k, k, dimension)
        u = np.random.uniform(0,1,1)
        if u[0] <= p(w):
            return w
            


W = np.array([
    generate_random(gaussian_fourier_tranform, dimension, 5/dimension)
    for _ in range(size)
])
W



array([[ 0.18106576,  0.11042719,  0.06276993, -0.16113171,  0.34293475,
         0.05466988,  0.02267549,  0.15303146,  0.11240464,  0.12548485],
       [ 0.25919679,  0.19209182,  0.45991895, -0.40282708,  0.11216274,
        -0.42000514, -0.27917223,  0.25757403, -0.07921108, -0.28830842],
       [ 0.2641046 , -0.36511289,  0.28727384,  0.49212797, -0.27956602,
         0.47017886,  0.03775285,  0.34608066,  0.19279248,  0.04905849],
       [ 0.42141911,  0.28257757, -0.34744009,  0.4429152 , -0.03684087,
        -0.41340311, -0.02388822, -0.03688797,  0.14629304,  0.23346875],
       [ 0.09293828, -0.07342647, -0.20090647, -0.026824  ,  0.1133675 ,
        -0.43121018, -0.25263524,  0.34695447,  0.13326951,  0.47935853]])

heurística de $k$



In [13]:
from random_feature.kernels import gaussian_fourier_tranform
dimension = 4
k = 3
np.random.seed(1)
generate_random(gaussian_fourier_tranform, dimension, k)


array([ 0.02026566,  0.16296105, -1.27152247,  0.07199538])

In [7]:
np.exp(-4)

10 / dimension 

2.5

In [37]:
import numpy as np 
k = 100
dimension = 3
b = np.random.uniform(-k, k, dimension)
W = np.random.uniform(-k, k, (dimension, 2))
x = np.random.uniform(-k, k, 2)
'''
b = np.array([0,1,-1])
W = np.array(
    [[1,0],
    [0,3],
    [2,4]]
)
x = np.array([1,0])
'''

'\nb = np.array([0,1,-1])\nW = np.array(\n    [[1,0],\n    [0,3],\n    [2,4]]\n)\nx = np.array([1,0])\n'

In [38]:
print('W \n',W)
X = np.repeat([x], dimension, axis=0)
print('repeated x\n',X) 
w_dot_x = np.sum(np.multiply(W, X), axis=1)
np.cos(w_dot_x + b)


W 
 [[ 56.71681314  -3.17999348]
 [ 41.44712723  -9.72595664]
 [ 63.68881002 -56.20425406]]
repeated x
 [[-51.51449283 -65.02461848]
 [-51.51449283 -65.02461848]
 [-51.51449283 -65.02461848]]


array([ 0.87313283, -0.96417883,  0.99909805])